// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkD0tWH3oaVGbayesiScfqREdufrPDc8s',
    appId: '1:644932001464:web:d9b31147f7562c3b825e4d',
    messagingSenderId: '644932001464',
    projectId: 'chatapp-1b5e0',
    authDomain: 'chatapp-1b5e0.firebaseapp.com',
    storageBucket: 'chatapp-1b5e0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn2c5NET6DygoaOj_c1R2EF3COGqmPH5M',
    appId: '1:644932001464:android:e6acd26a5fbe76e5825e4d',
    messagingSenderId: '644932001464',
    projectId: 'chatapp-1b5e0',
    storageBucket: 'chatapp-1b5e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXOKqF9RQcrvuHHFrP6n_zsbB2Ir4cncs',
    appId: '1:644932001464:ios:28390e08674b6271825e4d',
    messagingSenderId: '644932001464',
    projectId: 'chatapp-1b5e0',
    storageBucket: 'chatapp-1b5e0.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXOKqF9RQcrvuHHFrP6n_zsbB2Ir4cncs',
    appId: '1:644932001464:ios:28390e08674b6271825e4d',
    messagingSenderId: '644932001464',
    projectId: 'chatapp-1b5e0',
    storageBucket: 'chatapp-1b5e0.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkD0tWH3oaVGbayesiScfqREdufrPDc8s',
    appId: '1:644932001464:web:0eb2c65b23fa071e825e4d',
    messagingSenderId: '644932001464',
    projectId: 'chatapp-1b5e0',
    authDomain: 'chatapp-1b5e0.firebaseapp.com',
    storageBucket: 'chatapp-1b5e0.firebasestorage.app',
  );
}
